insert into department(name) values('software')
insert into department(name) values('mechanical')
insert into department(name) values('biotech')
insert into department(name) values('civil')
insert into department(name) values('electronics')
insert into department(name) values('electrical')
